### ISSUE TITLE
matplotlib issue

### ISSUE THREAD

**Issue by josephhughes** [centre-for-virus-research/weeSAM#13]
weeSAM --bam SARS-CoV-2.bam --html SARS1 --overwrite
/usr/local/bin/weeSAM:54: UserWarning:
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.
The backend was *originally* set to 'TkAgg' by the following code:
  File "/usr/local/bin/weeSAM", line 52, in <module>
    import seaborn as sb
  File "/opt/miniconda3/lib/python3.7/site-packages/seaborn/__init__.py", line 2, in <module>
    from .rcmod import *  # noqa: F401,F403
  File "/opt/miniconda3/lib/python3.7/site-packages/seaborn/rcmod.py", line 7, in <module>
    from . import palettes
  File "/opt/miniconda3/lib/python3.7/site-packages/seaborn/palettes.py", line 9, in <module>
    from .utils import desaturate, get_color_cycle
  File "/opt/miniconda3/lib/python3.7/site-packages/seaborn/utils.py", line 14, in <module>
    import matplotlib.pyplot as plt
  File "/opt/miniconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 71, in <module>
    from matplotlib.backends import pylab_setup
  File "/opt/miniconda3/lib/python3.7/site-packages/matplotlib/backends/__init__.py", line 17, in <module>
    line for line in traceback.format_stack()
  matplotlib.use('agg')
----	Processing: SARS-CoV-2.bam	----
Total # Mapped Reads:	212313
Total # Unmapped Reads:	0
Total # Reads:	212313
Generating a depth file, this may take a while.
Processing:	SARS-CoV-2	....
Traceback (most recent call last):
  File "/usr/local/bin/weeSAM", line 797, in <module>
    process_bam(bam_list)
  File "/usr/local/bin/weeSAM", line 657, in process_bam
    fig = my_plot(min_dict[i], i)
  File "/usr/local/bin/weeSAM", line 343, in my_plot
    fig = plt.figure(figsize=(16, 6))
  File "/opt/miniconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/opt/miniconda3/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/opt/miniconda3/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by mvvucak** [comment]
I'm unable to reproduce this on Alpha with my set-up. Could you tell me what versions of seaborn and matplotlib your environment is using? Also, is this happening on a local machine or while connecting to Alpha remotely?

 It looks like Seaborn is setting matplotlib's backend to 'TkAgg' which is interactive and requires ssh -X or ssh -Y to function. Might be a quick fix if that's the issue.

**Comment by josephhughes** [comment]
This isn't on Alpha.
I'm thinking we may need to test weeSAM on more systems or roll-it back to
a version with fewer dependencies.
